/** Build-only SVG -> packed monochrome sprites. No Iconify data ships to a device. */
import { createRequire } from "node:module";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import sharp from "sharp";
import { pixelGrid, orthogonalPaths } from "./pixel-grid.mjs";
const require = createRequire(import.meta.url);
const root = new URL("../../../../", import.meta.url);
const iconDir = new URL("device/sdk/icons/", root);
const prefixes = ["pixelarticons", "streamline-pixel"];
const sets = prefixes.map((prefix) => ({
  data: require(`@iconify-json/${prefix}/icons.json`),
  info: require(`@iconify-json/${prefix}/info.json`),
  version: require(`@iconify-json/${prefix}/package.json`).version,
}));
const catalog = new URL("catalog.html", iconDir);
const demo = new URL("public/device/streamline-coffee.png", root);
const template = await readFile(
  new URL("catalog-template.html", import.meta.url),
  "utf8",
);
const hash = createHash("sha256")
  .update(JSON.stringify(sets))
  .update(template)
  .update(await readFile(new URL(import.meta.url)))
  .update(
    await readFile(new URL("./pixel-grid.mjs", import.meta.url)),
  )
  .digest("hex");
const header = `// Generated by \`dui icons\`. Source hash: ${hash}\n`;
async function existing(path) {
  return readFile(path, "utf8").catch(() => "");
}
async function compactSprite(body) {
  const small = orthogonalPaths(body)
    .map(
      (points) =>
        `<path d="${points.map((p) => (p.op === "Z" ? "Z" : `${p.op}${Math.round(p.x / 2)} ${Math.round(p.y / 2)}`)).join("")}"/>`,
    )
    .join("");
  const rgba = await sharp(
    Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12">${small}</svg>`,
    ),
  )
    .ensureAlpha()
    .raw()
    .toBuffer();
  const bytes = Buffer.alloc(18);
  for (let i = 0; i < 144; i++)
    if (rgba[4 * i + 3] >= 128) bytes[i >> 3] |= 128 >> (i & 7);
  return bytes;
}
if (
  !(await existing(catalog)) ||
  !(await existing(demo)) ||
  !(
    await existing(new URL("system.ts", iconDir))
  ).startsWith(header) ||
  !(await existing(new URL("device/ui/src/status_icons.rs", root))).startsWith(
    header,
  ) ||
  (
    await Promise.all(
      prefixes.map((prefix) =>
        existing(new URL(`${prefix}.ts`, iconDir)),
      ),
    )
  ).some((file) => !file.startsWith(header))
) {
  const sprites = {};
  const hidden = [];
  for (const { data } of sets) {
    for (const name of [
      ...Object.keys(data.icons),
      ...Object.keys(data.aliases ?? {}),
    ].sort()) {
      let icon = data.icons[name];
      if (!icon) {
        const alias = data.aliases[name];
        if (Object.keys(alias).some((key) => key !== "parent"))
          throw new Error(`Unsupported alias transform: ${name}`);
        icon = data.icons[alias.parent];
      }
      const normalized =
        data.prefix === "streamline-pixel" ? pixelGrid(icon.body) : icon;
      const width = normalized.width ?? data.width ?? 16;
      const height = normalized.height ?? data.height ?? 16;
      const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" color="black">${normalized.body}</svg>`;
      const pixels = await sharp(Buffer.from(svg))
        .ensureAlpha()
        .raw()
        .toBuffer();
      const bits = Buffer.alloc(Math.ceil((width * height) / 8));
      for (let i = 0; i < width * height; i++) {
        const luminance =
          (pixels[4 * i] + pixels[4 * i + 1] + pixels[4 * i + 2]) / 3;
        if (pixels[4 * i + 3] >= 128 && luminance < 128)
          bits[i >> 3] |= 128 >> (i & 7);
      }
      sprites[`${data.prefix}:${name}`] = [width, height, bits.toString("hex")];
      if (icon.hidden || data.aliases?.[name])
        hidden.push(`${data.prefix}:${name}`);
      if (data.prefix === "streamline-pixel" && name === "food-drink-coffee") {
        await mkdir(new URL("public/device/", root), { recursive: true });
        await sharp(Buffer.from(svg))
          .flatten({ background: "white" })
          .png()
          .toFile(demo.pathname);
      }
    }
  }
  await mkdir(iconDir, { recursive: true });
  for (const prefix of prefixes) {
    const names = new Set();
    const exports = Object.entries(sprites)
      .filter(([name]) => name.startsWith(prefix + ":"))
      .map(([name, [width, height, hex]]) => {
        const pascal = name
          .split(":")[1]
          .split("-")
          .map((part) => part[0].toUpperCase() + part.slice(1))
          .join("");
        const component = /^\d/.test(pascal)
          ? `Icon${pascal}`
          : `${pascal}Icon`;
        if (names.has(component))
          throw new Error(`Duplicate icon export: ${component}`);
        names.add(component);
        return `export const ${component} = /* @__PURE__ */ createIcon(${width}, ${height}, "${hex}");`;
      });
    await writeFile(
      new URL(prefix + ".ts", iconDir),
      header +
        '// See ./licenses/README.md for attribution.\nimport { createIcon } from "./factory";\n' +
        exports.join("\n") +
        "\n",
    );
  }
  const statusIcons = {
    WIFI_OFF: "close",
    WIFI_0: "wifi",
    WIFI_1: "wifi",
    WIFI_2: "wifi",
    WIFI_3: "wifi",
    BATTERY_EMPTY: "battery",
    BATTERY_LOW: "battery-1",
    BATTERY_MEDIUM: "battery-2",
    BATTERY_FULL: "battery-full",
  };
  // Retain the licensed Wi-Fi glyph's original shapes; weaker signals omit outer arcs.
  // These indices identify closed rectangles in the pinned upstream wifi SVG path.
  const wifiBody = sets[0].data.icons.wifi.body;
  const wifiSegments = orthogonalPaths(wifiBody)
    .flat()
    .map((p) => (p.op === "Z" ? "Z" : `${p.op}${p.x} ${p.y}`))
    .join("")
    .match(/M[^M]+/g);
  if (wifiSegments.length !== 16)
    throw new Error("Upstream Wi-Fi geometry changed");
  const wifiLevels = [[0], [0, 1, 2, 3], [0, 1, 2, 3, 4, 5, 6, 14, 15]];
  const statusDeclarations = await Promise.all(
    Object.entries(statusIcons).map(async ([constant, name]) => {
      let body = sets[0].data.icons[name].body;
      const level = /^WIFI_([012])$/.exec(constant);
      if (level) {
        const path = wifiLevels[Number(level[1])]
          .map((i) => wifiSegments[i])
          .join("");
        body = `<path d="${path}"/>`;
      }
      // Rasterize small status glyphs from snapped vectors, never from a reduced bitmap.
      // The upstream 2-unit strokes become exactly one pixel at this 12px size.
      const bytes = await compactSprite(body);
      return `pub const ${constant}: &[u8] = &[${[...bytes].join(",")}];`;
    }),
  );
  await writeFile(
    new URL("device/ui/src/status_icons.rs", root),
    header +
      "// Pixelarticons (MIT), device/sdk/icons/licenses/.\n" +
      statusDeclarations.join("\n") +
      "\n",
  );
  const compactNames = {
    CreditCardIcon: "credit-card",
    DeviceLaptopIcon: "device-laptop",
    ChartIcon: "chart",
    ImageIcon: "image",
    SlidersIcon: "sliders",
    DatabaseIcon: "database",
    CpuIcon: "cpu",
  };
  const compactDeclarations = await Promise.all(
    Object.entries(compactNames).map(async ([name, source]) => {
      const bytes = await compactSprite(sets[0].data.icons[source].body);
      return `export const ${name} = /* @__PURE__ */ createIcon(12, 12, "${bytes.toString("hex")}");`;
    }),
  );
  await writeFile(
    new URL("system.ts", iconDir),
    header +
      '// Pixelarticons (MIT), ./licenses/.\nimport { createIcon } from "./factory";\n' +
      compactDeclarations.join("\n") +
      "\n",
  );
  const metadata = sets.map(({ info, version }) => ({ ...info, version }));
  await writeFile(
    catalog,
    template.replace(
      "/* ICON_DATA */",
      `const sprites = ${JSON.stringify(sprites)}; const hidden = new Set(${JSON.stringify(hidden)}); const collections = ${JSON.stringify(metadata)};`,
    ),
  );
  console.log(
    `Device icons: ${Object.keys(sprites).length} names, 1-bit sprites + offline catalogue`,
  );
} else console.log("Device icons: up to date");
