/**
 * Lucide (the site's icon set) as device icons: vector data only. Each icon is drawn at compile
 * time by ../../icons/vector.ts at the size an app uses it, so no bitmap set ships here.
 * Also draws the host's status sprites (Wi-Fi, battery, charging) for device/ui.
 */
import { readFileSync } from "node:fs";
import { readFile, readdir, writeFile, copyFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { rasterize } from "../../icons/vector.ts";

const require = createRequire(import.meta.url);
const root = new URL("../../../../", import.meta.url);
const iconDir = new URL("device/sdk/icons/", root);
const lucide = dirname(require.resolve("lucide-react/package.json"));
const version = JSON.parse(await readFile(join(lucide, "package.json"), "utf8")).version;
const source = join(lucide, "dist/esm/icons");

// Aliases re-export a canonical file; keep each drawing once, under its own name. Code-unit order.
const drawings = (await readdir(source))
  .filter((f) => f.endsWith(".js"))
  .sort((a, b) => Number(a > b) - Number(a < b))
  .filter((file) => readFileSync(join(source, file), "utf8").includes("const __iconNode"));
const icons = await Promise.all(
  drawings.map(async (file) => {
    const { __iconNode } = await import(join(source, file));
    // React keys are not drawing data.
    const nodes = __iconNode.map(([tag, attributes]) => [tag, Object.fromEntries(Object.entries(attributes).filter(([name]) => name !== "key"))]);
    return [file.slice(0, -3), nodes];
  }),
);
const vector = await readFile(new URL("../../icons/vector.ts", import.meta.url));
const hash = createHash("sha256")
  .update(version)
  .update(JSON.stringify(icons))
  .update(vector)
  .update(await readFile(new URL(import.meta.url)))
  .digest("hex");
const header = `// Generated by \`dui icons\` from lucide-react ${version}. Source hash: ${hash}\n`;
const component = (name) => {
  const pascal = name
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
  return /^\d/.test(pascal) ? `Icon${pascal}` : `${pascal}Icon`;
};
const target = new URL("lucide.ts", iconDir);
const current = await readFile(target, "utf8").catch(() => "");
const statusTarget = new URL("device/ui/src/status_icons.rs", root);
const status = await readFile(statusTarget, "utf8").catch(() => "");
if (current.startsWith(header) && status.startsWith(header)) {
  console.log("Lucide icons: up to date");
} else {
  const names = new Set();
  const lines = icons.map(([name, nodes]) => {
    const id = component(name);
    if (names.has(id)) throw new Error(`Duplicate icon export: ${id}`);
    names.add(id);
    return `export const ${id} = /* @__PURE__ */ createVectorIcon(${JSON.stringify(nodes)});`;
  });
  await writeFile(
    target,
    header +
      "// Lucide (ISC), ./licenses/lucide.txt. Drawn at compile time at the size used; see ./vector.ts.\n" +
      'import { createVectorIcon } from "./factory";\n' +
      lines.join("\n") +
      "\n",
  );
  await copyFile(join(lucide, "LICENSE"), new URL("licenses/lucide.txt", iconDir));

  // The status bar's sprites: 24 px, 2 px strokes, exactly as the kit draws Lucide.
  const nodesOf = Object.fromEntries(icons);
  const sprites = {
    WIFI_OFF: "wifi-off",
    WIFI_0: "wifi-zero",
    WIFI_1: "wifi-low",
    WIFI_2: "wifi-high",
    WIFI_3: "wifi",
    BATTERY_EMPTY: "battery",
    BATTERY_LOW: "battery-low",
    BATTERY_MEDIUM: "battery-medium",
    BATTERY_FULL: "battery-full",
    BATTERY_WARNING: "battery-warning",
    BATTERY_CHARGING: "battery-charging",
    PLUGGED: "plug-zap",
  };
  const declarations = Object.entries(sprites).map(([constant, name]) => {
    const { bits } = rasterize([{ nodes: nodesOf[name], stroke: 2 }], 24);
    return `pub const ${constant}: &[u8] = &[${bits.join(",")}];`;
  });
  await writeFile(
    statusTarget,
    header +
      "// Lucide (ISC), device/sdk/icons/licenses/lucide.txt. 24 × 24, packed 1-bit.\n" +
      declarations.join("\n") +
      "\n",
  );
  console.log(`Lucide icons: ${icons.length} vector icons, ${declarations.length} status sprites`);
}
