/** Shared by the build command and its reproducibility checks. */
export function rustScreenManifest(names: string[]): string {
  return [
    "// Generated by scripts/build-terminal-ui.mjs; edit screens/terminal.tsx instead.",
    "pub const DEFINITIONS: &[(&str, &[u8])] = &[",
    ...names.map(
      (name) =>
        `    ("${name}", include_bytes!("../../screens/compiled/${name}.dui")),`,
    ),
    "];",
    "",
  ].join("\n");
}

/** Avoid touching included binaries when their content is unchanged, so cargo/watch can reuse builds. */
export async function writeIfChanged(
  path: string,
  data: Uint8Array | string,
): Promise<void> {
  const { readFile, writeFile, mkdir } = await import("node:fs/promises");
  const { dirname } = await import("node:path");
  const next =
    typeof data === "string" ? Buffer.from(data, "utf8") : Buffer.from(data);
  try {
    if ((await readFile(path)).equals(next)) return;
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT"))
      throw error;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, next);
}
