/** Rust registry of a multi-screen app, so a host can `include_bytes!` every compiled screen by name. */
export function rustScreenManifest(
  names: string[],
  { source, includeDir }: { source: string; includeDir: string },
): string {
  return [
    `// Generated by \`dui build\` from ${source}; edit the TSX screens instead.`,
    "pub const DEFINITIONS: &[(&str, &[u8])] = &[",
    ...names.map(
      (name) => `    ("${name}", include_bytes!("${includeDir}/${name}.dui")),`,
    ),
    "];",
    "",
  ].join("\n");
}

/** Avoid touching included binaries when their content is unchanged, so cargo/watch can reuse builds. */
export async function writeIfChanged(
  path: string,
  data: Uint8Array | string,
): Promise<void> {
  const { readFile, writeFile, mkdir } = await import("node:fs/promises");
  const { dirname } = await import("node:path");
  const next =
    typeof data === "string" ? Buffer.from(data, "utf8") : Buffer.from(data);
  try {
    if ((await readFile(path)).equals(next)) return;
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT"))
      throw error;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, next);
}
