-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "caffeineMg" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "sugarGrams" DOUBLE PRECISION NOT NULL DEFAULT 25,
ADD COLUMN     "volumeMl" INTEGER NOT NULL DEFAULT 500;
