// Generated by bun run device:icons. Source hash: c9ca044ef4c13385f7b3c4b36c1c9b1a0a3d174e25691ef9664ef4e98be0b563
// Pixelarticons (MIT), authoring/art/licenses/.
pub const WIFI_OFF: &[u8] = &[0,0,0,0,1,4,8,128,80,2,0,80,8,129,4,0,0,0];
pub const WIFI_0: &[u8] = &[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0];
pub const WIFI_1: &[u8] = &[0,0,0,0,0,0,0,0,0,0,0,112,8,128,0,2,0,0];
pub const WIFI_2: &[u8] = &[0,0,0,0,0,0,0,0,240,16,130,116,8,128,0,2,0,0];
pub const WIFI_3: &[u8] = &[0,0,0,15,129,4,32,36,241,16,130,116,8,128,0,2,0,0];
pub const BATTERY_EMPTY: &[u8] = &[0,0,0,0,3,252,64,68,6,64,100,6,64,67,252,0,0,0];
pub const BATTERY_LOW: &[u8] = &[0,0,0,0,7,252,64,69,6,80,101,6,64,71,252,0,0,0];
pub const BATTERY_MEDIUM: &[u8] = &[0,0,0,0,7,252,64,69,70,84,101,70,64,71,252,0,0,0];
pub const BATTERY_FULL: &[u8] = &[0,0,0,0,3,252,64,69,86,85,101,86,64,67,252,0,0,0];
