// Generated by `dui icons`. Source hash: f4919fda22adf8d19a4e5166c04e61c846b66f2f92608a25b1669a1a2ad18943
// Pixelarticons (MIT), ./licenses/.
import { createIcon } from "./factory";
export const CreditCardIcon = /* @__PURE__ */ createIcon(12, 12, "0000003fc4027fe7fe4025c24023fc000000");
export const DeviceLaptopIcon = /* @__PURE__ */ createIcon(12, 12, "0000003fc2042042042043fc0007fe000000");
export const ChartIcon = /* @__PURE__ */ createIcon(12, 12, "0003fc4024024224224a24aa4aa4023fc000");
export const ImageIcon = /* @__PURE__ */ createIcon(12, 12, "0003fc40248254248240a4564a25123fc000");
export const SlidersIcon = /* @__PURE__ */ createIcon(12, 12, "00000012417410402472412012e124000000");
export const DatabaseIcon = /* @__PURE__ */ createIcon(12, 12, "0000f030c40240270e4f270e4f230c0f0000");
export const CpuIcon = /* @__PURE__ */ createIcon(12, 12, "0000a81fc20267328a68b28a6732021fc0a8");
